## IMPORTING MODULES

In [3]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder as leo
from sklearn.neural_network import MLPClassifier
!pip install Bio
from Bio import SeqIO
import csv


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.0/281.0 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 22.8 MB/s eta 0:00:00


## LOADING THE DATA AS A TEXT INTO A LIST OF LISTS

In [4]:
sq = SeqIO.read("chr22.fa", "fasta")
final = sq.seq
f = str(final)

## CREATING DATAFRAME

In [5]:
df = pd.read_csv("demo_data5.csv")
x = df.values
x = np.delete(x, 2, axis=1)
y = df['Label'].values
print(x)
print(y)

[['CCCTAA' 'Homo sapiens']
 ['GAGTTG' 'Homo sapiens']
 ['GGGATT' 'Homo sapiens']
 ['TTGTCC' 'Botryllus schlosseri']
 ['TGTCCC' 'Oikopleura dioica']
 ['TTAGGG' 'Botryllus schlosseri']
 ['GTCCCA' 'Homo sapiens']
 ['TCCCAA' 'Botryllus schlosseri']
 ['TTAGGG' 'Argopecten irradians']
 ['CCCAAA' 'Ciona savignyi']
 ['CCAAAG' 'Donax trunculus']
 ['GAGGTA' 'Oikopleura dioica']
 ['TTAGGG' 'Donax trunculus']
 ['GGTAAT' 'Homo sapiens']
 ['GGGATT' 'Botryllus schlosseri']
 ['AGAGAA' 'Homo sapiens']
 ['TTAGGG' 'Strongylocentrotus purpuratus']
 ['GAGAAG' 'Oikopleura dioica']
 ['AGCTGC' 'Botryllus schlosseri']
 ['GCCCTC' 'Homo sapiens']
 ['CCCTAA' 'Oikopleura dioica']
 ['GCCATG' 'Oikopleura dioica']
 ['ACAGCT' 'Botryllus schlosseri']
 ['CAGCTT' 'Homo sapiens']
 ['AATCCC' 'Homo sapiens']
 ['AGCCCT' 'Botryllus schlosseri']
 ['CCTAGG' 'Oikopleura dioica']
 ['TTAGGG' 'Homo sapiens']
 ['AGGGAA' 'Homo sapiens']
 ['GGGATT' 'Argopecten irradians']
 ['AATCCC' 'Oikopleura dioica']
 ['GGAACA' 'Homo sapiens']
 ['A

## SPLITTING OF DATA INTO TRAINING AND TEST DATA

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.3,random_state=3)

print(X_test)
print(Y_train)


[['AAGCAT' 'Homo sapiens']
 ['AGCCCT' 'Botryllus schlosseri']
 ['GGGATT' 'Botryllus schlosseri']
 ['CCCTAA' 'Donax trunculus']
 ['TAAAC' 'Diacanthous undosus']
 ['GACCC' 'Leptinotarsa decemlineata']
 ['AATCC' 'Melanotus legatus']
 ['ACACAT' 'Argopecten irradians']
 ['TTAGGG' 'Donax trunculus']
 ['TTGTCC' 'Botryllus schlosseri']
 ['GAGGG' 'Leptinotarsa decemlineata']
 ['GTCCCA' 'Homo sapiens']
 ['AGAAAG' 'Homo sapiens']
 ['ACACTC' 'Homo sapiens']
 ['TCTGA' 'Stegobium paniceum']
 ['CCCAA' 'Leptinotarsa decemlineata']
 ['GATTCT' 'Homo sapiens']
 ['TTAAAC' 'Oikopleura dioica']
 ['GGATT' 'Leptinotarsa decemlineata']
 ['TGCAA' 'Gammarus pulex']
 ['CCTAA' 'Leptinotarsa decemlineata']
 ['GGGATT' 'Ciona savignyi']
 ['TGTCCC' 'Oikopleura dioica']
 ['CCTAA' 'Graphoderus cinereus']
 ['CCTCTG' 'Botryllus schlosseri']
 ['TTTAT' 'Gammarus pulex']
 ['CCCTAA' 'Strongylocentrotus purpuratus']
 ['AATCC' 'Ampedus sanguineus']
 ['CCTGA' 'Tribolium audax']
 ['TTAAC' 'Ampedus sanguineus']
 ['CCTAA' 'Melanotu

## FITING OF MODEL

In [7]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
myleo = leo()
y_train_new = myleo.fit_transform(Y_train)
y_test_new = myleo.fit_transform(Y_test)
x_train_new1 = myleo.fit_transform(X_train[:,0])
x_train_new2 = myleo.fit_transform(X_train[:,1])
x_test_new1 = myleo.fit_transform(X_test[:,0])
x_test_new2 = myleo.fit_transform(X_test[:,1])
x_train_new = []
x_test_new = []
for i in range(len(x_train_new1)):
    x_train_new.append([x_train_new1[i], x_train_new2[i]])
for j in range(len(x_test_new1)):
    x_test_new.append([x_test_new1[j], x_test_new2[j]])

sc = StandardScaler()
x_train_new = sc.fit_transform(x_train_new)
x_test_new = sc.transform(x_test_new)
print(x_train_new)
print(x_test_new)
cls = SVC()
cls.fit(x_train_new, y_train_new)



[[-0.61504232  0.02658981]
 [ 1.60145552 -1.7682227 ]
 [ 1.4607255  -1.095168  ]
 [ 0.58116287 -1.7682227 ]
 [-1.52978746  0.47529294]
 [ 0.1589728   0.02658981]
 [ 0.58116287 -1.54387113]
 [-1.45942245  0.02658981]
 [-1.42423994  0.25094138]
 [ 0.19415531 -0.87081644]
 [-1.24832741 -0.19776175]
 [ 1.4607255  -1.31951957]
 [-0.05212223  0.25094138]
 [ 1.4607255   0.25094138]
 [ 1.425543    0.69964451]
 [-0.5094948   1.82140233]
 [ 1.425543    1.14834763]
 [ 1.07371794  0.25094138]
 [-1.42423994 -0.87081644]
 [ 0.61634537 -1.54387113]
 [-1.35387493 -1.095168  ]
 [-1.45942245  0.02658981]
 [ 1.14408295 -0.19776175]
 [ 1.21444797 -0.64646488]
 [-1.63533497  0.25094138]
 [-1.45942245 -0.64646488]
 [-0.4743123  -0.19776175]
 [ 1.00335293 -0.19776175]
 [-0.54467731 -0.87081644]
 [-1.42423994 -1.095168  ]
 [-0.89650236 -1.095168  ]
 [ 1.4607255   0.92399607]
 [ 0.93298792  1.59705076]
 [ 1.4607255   1.3726992 ]
 [ 0.44043285  0.25094138]
 [ 1.39036049 -1.54387113]
 [-0.12248724 -1.7682227 ]
 

SVC()

## SVM

In [8]:
y_pred = cls.predict(x_test_new)
print(y_pred)
print(y_test_new)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test_new, y_pred)
print(cm)
accuracy_score(y_test_new, y_pred)



[0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0
 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]
[[35  6]
 [17  1]]


0.6101694915254238

## RANDOM FOREST

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train_new, y_train_new)
yp = rf.predict(x_test_new)
print(yp)
print(y_test_new)
c = confusion_matrix(y_test_new, yp)
print(c)
accuracy_score(y_test_new, yp)

[0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 0 1 0 1 1
 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0
 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]
[[25 16]
 [13  5]]


0.5084745762711864

## MULTI LAYER PERCEPTRON

In [10]:
from sklearn.neural_network import MLPClassifier
mc = MLPClassifier()
mc.fit(x_train_new, y_train_new)
ypr = mc.predict(x_test_new)
print(ypr)
print(y_test_new)
co = confusion_matrix(y_test_new, ypr)
print(co)
accuracy_score(y_test_new, ypr)


[0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0
 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]
[[34  7]
 [16  2]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


0.6101694915254238

## K-NEAREST-NEIGHBOUR

In [11]:
knn = KNeighborsClassifier()
knn.fit(x_train_new, y_train_new)
ky = knn.predict(x_test_new)
print(ky)
print(y_test_new)
conf = confusion_matrix(y_test_new, ky)
print(conf)
accuracy_score(y_test_new, ky)


[1 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1
 1 0 1 1 0 0 0 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0
 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]
[[24 17]
 [13  5]]


0.4915254237288136